name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-bats-version:
    runs-on: ["self-hosted"]

    steps:
        - run: ls
        - run: hostname
        - run: pwd

    